# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f09c85cb0ba2443960aea3db9413447a3dacd7053bdb8d58783ca16da31374d208ef24cfd92dd5c5cbea02c1d9d84229db44b58859fc36376e4ee3000b8a643c

test:
  secret_key_base: ce2e5711d9095efe2246fd4ce6cbbd86c4ffa50943d0b70cdd92ae6c312e13fe8794a31dccd0ac37c43864872e68bce588584cde4fb5c7817ab15ca0c5cac43e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
